version: "3.7"

services:
  mini-backend:
    build:
      - target: development
      - context: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: database

  postgres:
    image: postgres:13.2
    ports:
      - target: 3306
        published: 3306
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: ''
      DB_NAME: 'mini'
    env_file:
      - .env
