version: "3.7"

services:
  mini-backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    env_file:
      - .env
    command: "yarn run start:prod"

  db:
    image: postgres:13.2
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_DB: '${POSTGRES_PASSWORD}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
    restart: always
    env_file:
      - .env
