version: "3.7"

services:
  mini-backend:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_PASS: ''
      DB_USER: 'postgres'
      DB_HOST: 'localhost'
    command: "yarn run start:dev"

  postgres:
    image: postgres:13.2
    ports:
      - target: 5432
        published: 5432
    environment:
      DB_USER: root
      POSTGRES_PASSWORD: 'qwerty'
      DB_NAME: 'mini'
    env_file:
      - .env
